### ISSUE TITLE
Undefined function or variable 'overlapadd'.

### ISSUE THREAD

**Issue by sunjunlishi** [snsun/cgmm_mvdr#1]
Undefined function or variable 'overlapadd'.

**Comment by sunjunlishi** [comment]
http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/voicebox.html，thanks

**Comment by sunjunlishi** [comment]
could you supply c++ code？i support you a little money

**Comment by snsun** [comment]
Sorry. I don't have C++ code now.

**Comment by sunjunlishi** [comment]
你姓孙？俺也姓孙，能加你Q？

**Comment by sunjunlishi** [comment]
mvdr的 c++代码
https://github.com/robin1001/beamforming/blob/master/apply-mvdr.cc
https://github.com/robin1001/beamforming
![t1](https://user-images.githubusercontent.com/11845664/32688181-1279132c-c707-11e7-8d56-096162cf6934.png)
![t2](https://user-images.githubusercontent.com/11845664/32688183-19e559ea-c707-11e7-8284-9e0b3b7701c1.png)

**Comment by snsun** [comment]
这代码是我同学的，张彬彬的

**Comment by sunjunlishi** [comment]
你同学张彬彬的那个MVDR太慢了；对了output = mvdr(ffts, Rv, d);你这个里面的参数大致是noise的位置吗；对了我想用声源DOA的形式输入；你的mvdr是在频域上的处理呀？

**Comment by snsun** [comment]
他的代码很久了，我也忘了。
output=mvdr(ffts, Rv, d), ffts就是多通道语音的fft，Rv 就是噪声的多通道的相关矩阵，d就是目标语音的steering
vector，如果你有DOA,用DOA算一个d，带到这个函数里就可以了。
我的MVDR是在频域上处理的。

**Comment by sunjunlishi** [comment]
恩，https://github.com/jordi-adell/mcarray。这个项目，分两步处理，第一步检测 DOA，第二步用DOA，进行加强。但是我感觉效果一般。你的项目感觉好点。

**Comment by snsun** [comment]
我的微信Ssning2014, 以后可以多交流

**Comment by sunjunlishi** [comment]
你同学的速度不慢，我把 printf去掉了，速度很快
