### ISSUE TITLE
Undefined function or variable 'enframe'.

### ISSUE THREAD

**Issue by pchao6** [snsun/cgmm_mvdr#2]
Hello, there is an error when I run the test.m. How to solve it? Thanks.
```
Undefined function or variable 'enframe'.

Error in multi_fft (line 14)
tmp = enframe(wav(:, 1),win, frame_shift);
```

**Comment by snsun** [comment]
Hi,
You need enframe.m. You can download VoiceBox and add the path into your
matlab environment.

http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/voicebox.html

Best


2018-08-08 21:07 GMT+08:00 AI Enthusiast <notifications@github.com>:

**Comment by pchao6** [comment]
Solved it just now. Thanks a lot.
