### ISSUE TITLE
calculating mvdr using Rv

### ISSUE THREAD

**Issue by hangtingchen** [snsun/cgmm_mvdr#3]
Thank you for your code.  I have a question about function mvdr. 
https://github.com/snsun/cgmm_mvdr/blob/cfc88aec4e26a6536eb4642566db9701ee9d6369/test.m#L37
According to your description of function mvdr, i think that Ry should be used instead of Rv. Refer to the Eq(9) in 

> Higuchi T , Ito N , Araki S , et al. Online MVDR Beamformer Based on Complex Gaussian Mixture Model With Spatial Prior for Noise Robust ASR[J]. IEEE/ACM Transactions on Audio, Speech, and Language Processing, 2017, 25(4):780-793.

**Comment by snsun** [comment]
Hi，

In theory, for MVDR, using Rv is equivalent to use Ry. As for my
experience,  Rv can get better results.

Best


hangtingchen <notifications@github.com> 于2019年2月19日周二 下午7:16写道：

**Comment by hangtingchen** [comment]
Thanks a lot for your reply. I just found that for test_wav/test1, it seemed using Rv suffered from larger distortion than using Ry. In addition, could you tell me the paper of the theory using Rv and Ry. 
Thanks for your patience.

**Comment by hangtingchen** [comment]
Thanks a lot for your reply. I just found that for test_wav/test1, it seemed using Rv suffered from larger distortion than using Ry. In addition, could you tell me the paper of the theory using Rv and Ry.
Thanks for your patience.

**Comment by snsun** [comment]
For MVDR,
w = min_w {w*R_{yy}*w}  with the constraint w^H * w = 1;
where y = x + n;
When we estimate R_{yy}, expection is used as eq9. R_{yy} = E[y * y^H] =
E[x * x^H] + E[n * n^H] = R_{xx} + R_{nn};

If we want to minimize  w*R_{yy}*w without any distortion for desired
signal x, we only need to minimize w*R_{nn}*w.

I can not remember the paper or book I have read. In many papers, R_{nn} is
commonly adopted to estimate MVDR coefficients.

Best
Sining

hangtingchen <notifications@github.com> 于2019年2月19日周二 下午7:55写道：

**Comment by hangtingchen** [comment]
Got it. Much appreciated.
